
version: '3.8'
services:
  scraper:
    build: .
    ports:
            - "2112:2112"
    restart: unless-stopped
    environment:
            - SERPAPI_KEY=${SERPAPI_KEY}

  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
            - "9090:9090"
    volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
            - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:10.4.0
    ports:
            - "3000:3000"
    environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
            - prometheus